In [1]:
import numpy as np


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)


[[1 2]
 [3 4]]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A.shape)
print(A.size)
print(A.ndim)

(2, 2)
4
2


In [7]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.diag([1, 2, 3])


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print(C)
2 * A


[[ 6  8]
 [10 12]]


array([[2, 4],
       [6, 8]])

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A.dot(B)
A @ B


array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
